"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { eq } from "drizzle-orm";

import { z } from "zod";

import { expandMission } from "@ayeastra/ai";
import { currentContext } from "@ayeastra/core";
import { entities, getDb, missions, reports, scopedDb } from "@ayeastra/db";
import { getWorkOS } from "@workos-inc/authkit-nextjs";
import { inArray } from "drizzle-orm";
import {
  canTransitionMission,
  parseReportLayout,
  templateByKey,
  watchSpecSchema,
} from "@ayeastra/workflow";

import { requireWorkflow } from "@/lib/workflow";

/** Mission Rooms + Reports server actions (3.2). Entitlement-gated. */

const CreateMissionInput = z.object({
  goal: z.string().trim().min(3).max(300),
  template: z.string().nullish(),
  entityIds: z.array(z.uuid()).min(1).max(10),
});

export async function createMission(formData: FormData) {
  const session = await requireWorkflow();
  const parsed = CreateMissionInput.safeParse({
    goal: formData.get("goal"),
    template: formData.get("template"),
    entityIds: formData.getAll("entityIds"),
  });
  if (!parsed.success) return;

  const scoped = scopedDb(session.organizationId);
  const template = templateByKey(parsed.data.template ?? "");

  // Template seeds the spec; the frontier expansion refines it when the
  // model is available (credential-gated grace — the seed already works).
  let spec = watchSpecSchema.parse({
    v: 1,
    categories: template?.categories ?? ["pricing", "launch", "messaging"],
    lookFor: template?.lookFor ?? [],
    leadingIndicators: template?.leadingIndicators ?? [],
  });
  let priorityId: string | null = null;
  try {
    const context = await currentContext(scoped);
    // The expansion prompt grounds on entity NAMES — resolve them; an org
    // model call also always carries the org for cost attribution.
    const named = await getDb()
      .select({ id: entities.id, name: entities.canonicalName })
      .from(entities)
      .where(inArray(entities.id, parsed.data.entityIds));
    const expanded = await expandMission.run(
      {
        goal: parsed.data.goal,
        entities: named,
        priorities:
          context?.payload.priorities
            .filter((p) => p.status === "active")
            .map((p) => ({ id: p.id, text: p.text })) ?? [],
      },
      { orgId: session.organizationId },
    );
    spec = watchSpecSchema.parse({
      v: 1,
      categories: expanded.categories,
      lookFor: expanded.lookFor,
      leadingIndicators: expanded.leadingIndicators,
    });
    priorityId = expanded.priorityId;
  } catch {
    // No model available or expansion failed — the template seed stands.
  }

  const [mission] = await scoped
    .insert(missions, {
      goal: parsed.data.goal,
      entityIds: parsed.data.entityIds,
      ownerUserId: session.user.id,
      watchSpec: spec,
      priorityId,
      memberUserIds: [session.user.id],
    })
    .returning();
  redirect(`/missions/${mission!.id}`);
}

const TransitionInput = z.object({
  missionId: z.uuid(),
  to: z.enum(["active", "closed"]),
});

export async function transitionMission(formData: FormData) {
  const session = await requireWorkflow();
  const parsed = TransitionInput.safeParse({
    missionId: formData.get("missionId"),
    to: formData.get("to"),
  });
  if (!parsed.success) return;

  const scoped = scopedDb(session.organizationId);
  const [mission] = await scoped.select(missions, eq(missions.id, parsed.data.missionId));
  if (!mission || !canTransitionMission(mission.status, parsed.data.to)) return;

  await scoped.update(
    missions,
    {
      status: parsed.data.to,
      ...(parsed.data.to === "closed" ? { closedAt: new Date() } : {}),
    },
    eq(missions.id, mission.id),
  );
  // Close-out retrospective is generated by the mission.retro job
  // (@ayeastra/workflow/jobs) once the jobs platform is wired.
  revalidatePath(`/missions/${mission.id}`);
  revalidatePath("/missions");
}

const AddMemberInput = z.object({
  missionId: z.uuid(),
  userId: z.string().trim().min(1).max(120),
});

export async function addMissionMember(formData: FormData) {
  const session = await requireWorkflow();
  const parsed = AddMemberInput.safeParse({
    missionId: formData.get("missionId"),
    userId: formData.get("userId"),
  });
  if (!parsed.success) return;

  const scoped = scopedDb(session.organizationId);
  const [mission] = await scoped.select(missions, eq(missions.id, parsed.data.missionId));
  if (!mission || mission.status === "closed") return;
  if (mission.memberUserIds.includes(parsed.data.userId)) return;

  // Only users who are active members of THIS org can join a mission —
  // an arbitrary id would leak org intelligence on brief/retro fan-out.
  const memberships = await getWorkOS().userManagement.listOrganizationMemberships({
    organizationId: session.organizationId,
    userId: parsed.data.userId,
    statuses: ["active"],
  });
  if (memberships.data.length === 0) return;

  await scoped.update(
    missions,
    { memberUserIds: [...mission.memberUserIds, parsed.data.userId] },
    eq(missions.id, mission.id),
  );
  revalidatePath(`/missions/${mission.id}`);
}

const CreateReportInput = z.object({
  title: z.string().trim().min(1).max(120),
  layout: z.string().min(2),
});

export async function createReport(formData: FormData) {
  const session = await requireWorkflow();
  const parsed = CreateReportInput.safeParse({
    title: formData.get("title"),
    layout: formData.get("layout"),
  });
  if (!parsed.success) return;

  let layout: unknown;
  try {
    layout = parseReportLayout(JSON.parse(parsed.data.layout));
  } catch {
    return; // invalid layout never lands (zod-gated)
  }

  const scoped = scopedDb(session.organizationId);
  const [report] = await scoped
    .insert(reports, {
      title: parsed.data.title,
      layout,
      createdBy: session.user.id,
    })
    .returning();
  redirect(`/reports/${report!.id}`);
}
